/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeFormRouteImport } from './routes/resumeForm'
import { Route as IndexRouteImport } from './routes/index'

const ResumeFormRoute = ResumeFormRouteImport.update({
  id: '/resumeForm',
  path: '/resumeForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumeForm': typeof ResumeFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumeForm': typeof ResumeFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resumeForm': typeof ResumeFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resumeForm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resumeForm'
  id: '__root__' | '/' | '/resumeForm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeFormRoute: typeof ResumeFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumeForm': {
      id: '/resumeForm'
      path: '/resumeForm'
      fullPath: '/resumeForm'
      preLoaderRoute: typeof ResumeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/resumeForm' {
  const createFileRoute: CreateFileRoute<
    '/resumeForm',
    FileRoutesByPath['/resumeForm']['parentRoute'],
    FileRoutesByPath['/resumeForm']['id'],
    FileRoutesByPath['/resumeForm']['path'],
    FileRoutesByPath['/resumeForm']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeFormRoute: ResumeFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
