/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateSelectorRouteImport } from './routes/template-selector'
import { Route as ResumeFormRouteImport } from './routes/resumeForm'
import { Route as ModernTemplateRouteImport } from './routes/modern-template'
import { Route as ClassicTemplateRouteImport } from './routes/classic-template'
import { Route as IndexRouteImport } from './routes/index'

const TemplateSelectorRoute = TemplateSelectorRouteImport.update({
  id: '/template-selector',
  path: '/template-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeFormRoute = ResumeFormRouteImport.update({
  id: '/resumeForm',
  path: '/resumeForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernTemplateRoute = ModernTemplateRouteImport.update({
  id: '/modern-template',
  path: '/modern-template',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicTemplateRoute = ClassicTemplateRouteImport.update({
  id: '/classic-template',
  path: '/classic-template',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classic-template': typeof ClassicTemplateRoute
  '/modern-template': typeof ModernTemplateRoute
  '/resumeForm': typeof ResumeFormRoute
  '/template-selector': typeof TemplateSelectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classic-template': typeof ClassicTemplateRoute
  '/modern-template': typeof ModernTemplateRoute
  '/resumeForm': typeof ResumeFormRoute
  '/template-selector': typeof TemplateSelectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classic-template': typeof ClassicTemplateRoute
  '/modern-template': typeof ModernTemplateRoute
  '/resumeForm': typeof ResumeFormRoute
  '/template-selector': typeof TemplateSelectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classic-template'
    | '/modern-template'
    | '/resumeForm'
    | '/template-selector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classic-template'
    | '/modern-template'
    | '/resumeForm'
    | '/template-selector'
  id:
    | '__root__'
    | '/'
    | '/classic-template'
    | '/modern-template'
    | '/resumeForm'
    | '/template-selector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassicTemplateRoute: typeof ClassicTemplateRoute
  ModernTemplateRoute: typeof ModernTemplateRoute
  ResumeFormRoute: typeof ResumeFormRoute
  TemplateSelectorRoute: typeof TemplateSelectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic-template': {
      id: '/classic-template'
      path: '/classic-template'
      fullPath: '/classic-template'
      preLoaderRoute: typeof ClassicTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern-template': {
      id: '/modern-template'
      path: '/modern-template'
      fullPath: '/modern-template'
      preLoaderRoute: typeof ModernTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumeForm': {
      id: '/resumeForm'
      path: '/resumeForm'
      fullPath: '/resumeForm'
      preLoaderRoute: typeof ResumeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-selector': {
      id: '/template-selector'
      path: '/template-selector'
      fullPath: '/template-selector'
      preLoaderRoute: typeof TemplateSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/classic-template' {
  const createFileRoute: CreateFileRoute<
    '/classic-template',
    FileRoutesByPath['/classic-template']['parentRoute'],
    FileRoutesByPath['/classic-template']['id'],
    FileRoutesByPath['/classic-template']['path'],
    FileRoutesByPath['/classic-template']['fullPath']
  >
}
declare module './routes/modern-template' {
  const createFileRoute: CreateFileRoute<
    '/modern-template',
    FileRoutesByPath['/modern-template']['parentRoute'],
    FileRoutesByPath['/modern-template']['id'],
    FileRoutesByPath['/modern-template']['path'],
    FileRoutesByPath['/modern-template']['fullPath']
  >
}
declare module './routes/resumeForm' {
  const createFileRoute: CreateFileRoute<
    '/resumeForm',
    FileRoutesByPath['/resumeForm']['parentRoute'],
    FileRoutesByPath['/resumeForm']['id'],
    FileRoutesByPath['/resumeForm']['path'],
    FileRoutesByPath['/resumeForm']['fullPath']
  >
}
declare module './routes/template-selector' {
  const createFileRoute: CreateFileRoute<
    '/template-selector',
    FileRoutesByPath['/template-selector']['parentRoute'],
    FileRoutesByPath['/template-selector']['id'],
    FileRoutesByPath['/template-selector']['path'],
    FileRoutesByPath['/template-selector']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassicTemplateRoute: ClassicTemplateRoute,
  ModernTemplateRoute: ModernTemplateRoute,
  ResumeFormRoute: ResumeFormRoute,
  TemplateSelectorRoute: TemplateSelectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
